#Initialize all connections into a dictionary that maps the source city to a list of all destinations
ConnectionList = {
    "Montreal" : ["Chicago", "New York", "Washington"],
    "Chicago" : ["Atlanta", "Montreal", "San Francisco", "Los Angeles"],
    "San Francisco" : ["Los Angeles", "Chicago", "Tokyo", "Manila"],
    "New York" : ["Montreal", "Washington", "London", "Madrid"],
    "Washington" : ["New York", "Atlanta", "Miami", "Montreal"],
    "Atlanta" : ["Chicago", "Washington", "Miami"],
    "London" : ["New York", "Madrid", "Paris", "Essen"],
    "Madrid" : ["New York", "London", "Paris", "Algiers", "Sao Paulo"],
    "Paris" : ["London", "Essen", "Milan", "Algiers", "Madrid"],
    "Essen" : ["London", "Paris", "Milan", "St. Petersburg"],
    "Milan" : ["Essen", "Paris", "Istanbul"],
    "St. Petersburg" : ["Essen", "Istanbul", "Moscow"],

    "Los Angeles" : ["Mexico City", "Chicago", "San Francisco", "Sydney"],
    "Mexico City" : ["Los Angeles", "Chicago", "Miami", "Bogota", "Lima"],
    "Miami" : ["Atlanta", "Washington", "Mexico City", "Bogota"],
    "Bogota" : ["Miami", "Mexico City", "Lima", "Buenos Aires", "Sao Paulo"],
    "Lima" : ["Mexico City", "Miami", "Santiago"],
    "Santiago" : ["Lima"],
    "Buenos Aires" : ["Bogota", "Sao Paulo"],
    "Sao Paulo" : ["Buenos Aires", "Bogota", "Madrid", "Lagos"],
    "Lagos" : ["Sao Paulo", "Kinshasa", "Khartoum"],
    "Khartoum" : ["Lagos", "Kinshasa", "Johannesburg"],
    "Kinshasa" : ["Lagos", "Khartoum", "Johannesburg"],
    "Johannesburg" : ["Kinshasa", "Khartoum"],

    "Algiers" : ["Madrid", "Paris", "Istanbul", "Cairo"],
    "Cairo" : ["Algiers", "Istanbul", "Baghdad", "Riyadh"],
    "Istanbul" : ["Algiers", "Cairo", "Baghdad", "Moscow", "St. Petersburg", "Milan"],
    "Moscow" : ["St. Petersburg", "Istanbul", "Tehran"],
    "Baghdad" : ["Istanbul", "Cairo", "Riyadh", "Karachi", "Tehran"],
    "Riyadh" : ["Cairo", "Baghdad", "Karachi"],
    "Tehran" : ["Moscow", "Baghdad", "Karachi", "Delhi"],
    "Karachi" : ["Baghdad", "Riyadh", "Mumbai", "Delhi", "Tehran"],
    "Delhi" : ["Tehran", "Karachi", "Mumbai", "Chennai", "Kolkata"],
    "Mumbai" : ["Karachi", "Delhi", "Chennai"],
    "Chennai" : ["Mumbai", "Delhi", "Kolkata", "Bangkok", "Jakarta"],
    "Kolkata" : ["Delhi", "Chennai", "Bangkok", "Hong Kong"],

    "Bangkok" : ["Kolkata", "Chennai", "Jakarta", "Ho Chi Minh City", "Hong Kong"],
    "Jakarta" : ["Chennai", "Bangkok", "Ho Chi Minh City", "Sydney"],
    "Ho Chi Minh City" : ["Jakarta", "Bangkok", "Hong Kong", "Manila"],
    "Sydney" : ["Jakarta", "Manila", "Los Angeles"],
    "Manila" : ["Ho Chi Minh City", "Hong Kong", "Taipei", "San Francisco", "Sydney"],
    "Taipei" : ["Shanghai", "Hong Kong", "Manila", "Osaka"],
    "Hong Kong" : ["Kolkata", "Bangkok", "Ho Chi Minh City", "Manila", "Taipei", "Shanghai"],
    "Shanghai" : ["Hong Kong", "Taipei", "Tokyo", "Seoul", "Beijing"],
    "Beijing" : ["Shanghai", "Seoul"],
    "Seoul" : ["Beijing", "Shanghai", "Tokyo"],
    "Tokyo" : ["Seoul", "Shanghai", "Osaka", "San Francisco"],
    "Osaka" : ["Taipei", "Tokyo"]
}
